apiVersion: v1
kind: Service
metadata:
  name: spud-stories
spec:
  type: LoadBalancer
  selector:
    app: spud-stories
    environment: production
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000