apiVersion: apps/v1
kind: Deployment
metadata:
  name: spud-stories
  labels:
    app: spud-stories
    environment: production
spec:
  replicas: 3
  selector:
    matchLabels:
      app: spud-stories
      environment: production
  template:
    metadata:
      labels:
        app: spud-stories
        environment: production
    spec:
      containers:
        - name: spud-stories
          image: armory/spud-stories:sha-b4236d6
          args:
            - --config
            - /opt/spud-stories/config/spudstories.yml
          ports:
            - containerPort: 3000
          volumeMounts:
            - mountPath: /opt/spud-stories/config
              name: config
      volumes:
        - name: config
          configMap:
            name: spud-stories-config
