apiVersion: apps/v1
kind: Deployment
metadata:
  name: spud-stories
  labels:
    app: spud-stories
    environment: production
spec:
  strategy:
    type: RollingUpdate
    rollingParams:
      updatePeriodSeconds: 20
      intervalSeconds: 5 
      timeoutSeconds: 120 
      maxSurge: "20%" 
      maxUnavailable: "5%" 
  replicas: 6
  selector:
    matchLabels:
      app: spud-stories
      environment: production
  template:
    metadata:
      labels:
        app: spud-stories
        environment: production
    spec:
      containers:
        - name: spud-stories
          image: armory/spud-stories:sha-ab23c9a
          args:
            - --num-objects
            - "4250"
            - --object-size
            - "2048"
          ports:
            - containerPort: 3000
          readinessProbe:
            httpGet:
              path: /
              port: 3000
          livenessProbe:
            httpGet:
              path: /
              port: 3000
