apiVersion: apps/v1
kind: Deployment
metadata:
  name: spud-stories
  labels:
    app: spud-stories
    environment: production
spec:
  replicas: 6
  selector:
    matchLabels:
      app: spud-stories
      environment: production
  template:
    metadata:
      labels:
        app: spud-stories
        environment: production
    spec:
      containers:
        - name: spud-stories
          image: armory/spud-stories:sha-ab23c9a
          args:
            - --num-objects
            - "4000"
            - --object-size
            - "2048"

          ports:
            - containerPort: 3000
          livenessProbe:
            httpGet:
              path: /
            port: 3000
